### ISSUE TITLE
Simple change to manifest

### ISSUE THREAD

**Issue by phil-tti** [jtviolet/block-reddit-login#1]
In the manifest.json file if you add a * to the end of the url for matching the plugin works on all pages not just the first one.

**Comment by jtviolet** [comment]
Fixed with commit [9bb004a417feb23366eae6a74f75c0dbf88c350a](https://github.com/jtviolet/block-reddit-login/commit/9bb004a417feb23366eae6a74f75c0dbf88c350a)
